"""Edge-AI congestion prediction (build prompt §10).

The JEC runs inference at the edge node every second on ITS local features.
Two predictors:

  1. HeuristicBaseline — persistence + inflow/outflow estimate (deterministic)
  2. CongestionMLP     — small numpy MLP (2 hidden layers) trained on data
     generated by the simulation itself

The training pipeline:
    python -m robotics_ws.congestion_predictor.dataset   (runs scenarios)
    python -m robotics_ws.congestion_predictor.train     (fits + evaluates)
Outputs are stored under datasets/ and models/ with an honest evaluation
report in results/predictor_eval.json. The runtime default predictor is
chosen by the evaluation verdict (spec: if ML fails to beat the heuristic,
the deterministic heuristic stays the default).
"""
from __future__ import annotations

import json
import math
import os
from typing import Any, Dict, List, Optional, Sequence

import numpy as np

FEATURE_ORDER = [
    "occ_now", "occ_prev", "occ_2ago", "approaching", "queue_len",
    "intent_count", "downstream_occ", "demand_factor", "blockage_active",
    "recent_blockages", "resv_active",
]


def features_vector(f: Dict[str, float]) -> List[float]:
    return [float(f.get(k, 0.0)) for k in FEATURE_ORDER]


# ---------------------------------------------------------------------------
class HeuristicBaseline:
    """Persistence + inflow/outflow: pred = occ + a*(inflow - outflow)."""

    name = "heuristic"

    def predict(self, f) -> float:
        if not isinstance(f, dict):
            f = {k: float(v) for k, v in zip(FEATURE_ORDER, f)}
        inflow = 0.85 * f.get("approaching", 0.0) + 0.30 * f.get("queue_len", 0.0)
        outflow = 0.55 * f.get("occ_now", 0.0) + 0.10 * f.get("occ_prev", 0.0)
        pred = f.get("occ_now", 0.0) + inflow - outflow
        return max(0.0, pred)


# ---------------------------------------------------------------------------
class CongestionMLP:
    """Tiny MLP (11 -> 24 -> 12 -> 1, ReLU) — numpy forward pass only.

    Inference cost: ~1k FLOPs — runs anywhere, including at the JEC edge node
    every second. Trained with Adam by train.py; weights stored as JSON.
    """

    name = "mlp"
    LAYOUT = (len(FEATURE_ORDER), 24, 12, 1)

    def __init__(self, weights: Optional[Dict[str, List[List[float]]]] = None,
                 scaler: Optional[Dict[str, List[float]]] = None):
        rng = np.random.default_rng(0)
        self.W: List[np.ndarray] = []
        self.b: List[np.ndarray] = []
        if weights:
            for i in range(len(self.LAYOUT) - 1):
                self.W.append(np.array(weights[f"W{i}"], dtype=float))
                self.b.append(np.array(weights[f"b{i}"], dtype=float))
        else:
            for i in range(len(self.LAYOUT) - 1):
                fin, fout = self.LAYOUT[i], self.LAYOUT[i + 1]
                self.W.append(rng.normal(0, math.sqrt(2.0 / fin), (fin, fout)))
                self.b.append(np.zeros(fout))
        self.mu = np.array(scaler["mu"]) if scaler else None
        self.sd = np.array(scaler["sd"]) if scaler else None

    # ------------------------------------------------------------------
    def forward(self, x: np.ndarray) -> np.ndarray:
        if self.mu is not None:
            x = (x - self.mu) / np.where(self.sd < 1e-9, 1.0, self.sd)
        a = x
        for i, (w, b) in enumerate(zip(self.W, self.b)):
            z = a @ w + b
            a = np.maximum(z, 0.0) if i < len(self.W) - 1 else z
        return a

    def predict(self, f: Dict[str, float]) -> float:
        x = np.array(features_vector(f))
        return max(0.0, float(self.forward(x.reshape(1, -1))[0, 0]))

    # ------------------------------------------------------------------
    def to_json(self) -> Dict[str, Any]:
        return {
            "layout": list(self.LAYOUT),
            "features": FEATURE_ORDER,
            "scaler": {"mu": self.mu.tolist() if self.mu is not None else None,
                       "sd": self.sd.tolist() if self.sd is not None else None},
            "weights": {f"W{i}": w.tolist() for i, w in enumerate(self.W)} |
                       {f"b{i}": b.tolist() for i, b in enumerate(self.b)},
        }

    @staticmethod
    def from_json(data: Dict[str, Any]) -> "CongestionMLP":
        mlp = CongestionMLP()
        mlp.W = [np.array(data["weights"][f"W{i}"], dtype=float)
                 for i in range(len(mlp.LAYOUT) - 1)]
        mlp.b = [np.array(data["weights"][f"b{i}"], dtype=float)
                 for i in range(len(mlp.LAYOUT) - 1)]
        mu = (data.get("scaler") or {}).get("mu")
        sd = (data.get("scaler") or {}).get("sd")
        mlp.mu = np.array(mu, dtype=float) if mu else None
        mlp.sd = np.array(sd, dtype=float) if sd else None
        return mlp


# ---------------------------------------------------------------------------
def load_predictor(cfg: Dict[str, Any]) -> Any:
    """Factory used by JECs: model choice from config + availability."""
    pconf = cfg.get("predictor", {})
    kind = pconf.get("model", "heuristic")
    if kind == "mlp":
        path = pconf.get("model_path", "models/congestion_mlp.json")
        if os.path.exists(path):
            try:
                with open(path) as f:
                    mlp = CongestionMLP.from_json(json.load(f))
                return mlp
            except Exception:  # noqa: BLE001 — fall back to heuristic
                pass
    return HeuristicBaseline()
